/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utp.registro_de_productos;

import com.formdev.flatlaf.FlatLightLaf;
import com.utp.registro_de_productos.controller.CategoryController;
import com.utp.registro_de_productos.controller.EmployeeController;
import com.utp.registro_de_productos.controller.ProductController;
import com.utp.registro_de_productos.controller.ReportsController;
import com.utp.registro_de_productos.controller.SupplierController;
import com.utp.registro_de_productos.model.CategoryModel;
import com.utp.registro_de_productos.model.ProductModel;
import com.utp.registro_de_productos.model.SupplierModel;
import com.utp.registro_de_productos.model.UserModel;
import com.utp.registro_de_productos.provider.ProductProvider;
import io.vavr.control.Either;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.TableModel;

/**
 *
 * @author israelgutierrez
 */
public class MainScreen extends javax.swing.JFrame {
    UserModel user;
    ArrayList<ProductModel> products = new ArrayList<>();
    /**
     * Creates new form MainScreen
     * @param user
     */
    public MainScreen(UserModel user) {
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closeSessionButton = new javax.swing.JButton();
        mainMenu = new javax.swing.JTabbedPane();
        productsPanel = new javax.swing.JPanel();
        productTabbedPane = new javax.swing.JTabbedPane();
        registerProductoPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        productAddButton = new javax.swing.JButton();
        productEditButton = new javax.swing.JButton();
        productDeleteButton = new javax.swing.JButton();
        registerCategoryPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        categoryAddButton = new javax.swing.JButton();
        categoryEditButton = new javax.swing.JButton();
        categoryDeleteButton = new javax.swing.JButton();
        registerSupplierPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        supplierAddButton = new javax.swing.JButton();
        supplierEditButton = new javax.swing.JButton();
        supplierDeleteButton = new javax.swing.JButton();
        peoplePanel = new javax.swing.JPanel();
        peopleTabbedPane = new javax.swing.JTabbedPane();
        registerEmployeePanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        employeeAddButton = new javax.swing.JButton();
        employeeEditButton = new javax.swing.JButton();
        employeeDeleteButton = new javax.swing.JButton();
        registerUserPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        userAddButton = new javax.swing.JButton();
        userEditButton = new javax.swing.JButton();
        userDeleteButton = new javax.swing.JButton();
        reportsPanel = new javax.swing.JPanel();
        peopleTabbedPane1 = new javax.swing.JTabbedPane();
        registerEmployeePanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        registerUserPanel1 = new javax.swing.JPanel();
        configurationPanel = new javax.swing.JPanel();
        controlPanel = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        peoplePanel6 = new javax.swing.JPanel();
        peoplePanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Control de Inventario");

        closeSessionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign-out-alt.png"))); // NOI18N
        closeSessionButton.setText("Cerrar Sesion");
        closeSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSessionButtonActionPerformed(evt);
            }
        });

        mainMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        registerProductoPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                registerProductoPanelComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                registerProductoPanelComponentShown(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripción", "Precio", "Cantidad", "Categoría", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(productTable);
        productTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(2).setResizable(false);
        }

        productAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        productAddButton.setText("Añadir");
        productAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAddButtonActionPerformed(evt);
            }
        });

        productEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        productEditButton.setText("Editar");
        productEditButton.setEnabled(false);
        productEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productEditButtonActionPerformed(evt);
            }
        });

        productDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        productDeleteButton.setText("Eliminar");
        productDeleteButton.setEnabled(false);
        productDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productAddButton)
                .addGap(18, 18, 18)
                .addComponent(productEditButton)
                .addGap(18, 18, 18)
                .addComponent(productDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(productDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerProductoPanelLayout = new javax.swing.GroupLayout(registerProductoPanel);
        registerProductoPanel.setLayout(registerProductoPanelLayout);
        registerProductoPanelLayout.setHorizontalGroup(
            registerProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerProductoPanelLayout.setVerticalGroup(
            registerProductoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerProductoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        productTabbedPane.addTab("Registro de productos", registerProductoPanel);

        registerCategoryPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                registerCategoryPanelComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                registerCategoryPanelComponentShown(evt);
            }
        });

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(categoryTable);
        categoryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (categoryTable.getColumnModel().getColumnCount() > 0) {
            categoryTable.getColumnModel().getColumn(2).setResizable(false);
        }

        categoryAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        categoryAddButton.setText("Añadir");
        categoryAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryAddButtonActionPerformed(evt);
            }
        });

        categoryEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        categoryEditButton.setText("Editar");
        categoryEditButton.setEnabled(false);
        categoryEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryEditButtonActionPerformed(evt);
            }
        });

        categoryDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        categoryDeleteButton.setText("Eliminar");
        categoryDeleteButton.setEnabled(false);
        categoryDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryAddButton)
                .addGap(18, 18, 18)
                .addComponent(categoryEditButton)
                .addGap(18, 18, 18)
                .addComponent(categoryDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoryAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(categoryDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerCategoryPanelLayout = new javax.swing.GroupLayout(registerCategoryPanel);
        registerCategoryPanel.setLayout(registerCategoryPanelLayout);
        registerCategoryPanelLayout.setHorizontalGroup(
            registerCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerCategoryPanelLayout.setVerticalGroup(
            registerCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        productTabbedPane.addTab("Registro de categorias", registerCategoryPanel);

        registerSupplierPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                registerSupplierPanelComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                registerSupplierPanelComponentShown(evt);
            }
        });

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "RUC", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(supplierTable);
        supplierTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (supplierTable.getColumnModel().getColumnCount() > 0) {
            supplierTable.getColumnModel().getColumn(2).setResizable(false);
        }

        supplierAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        supplierAddButton.setText("Añadir");
        supplierAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierAddButtonActionPerformed(evt);
            }
        });

        supplierEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        supplierEditButton.setText("Editar");
        supplierEditButton.setEnabled(false);
        supplierEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierEditButtonActionPerformed(evt);
            }
        });

        supplierDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        supplierDeleteButton.setText("Eliminar");
        supplierDeleteButton.setEnabled(false);
        supplierDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supplierAddButton)
                .addGap(18, 18, 18)
                .addComponent(supplierEditButton)
                .addGap(18, 18, 18)
                .addComponent(supplierDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplierAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(supplierDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerSupplierPanelLayout = new javax.swing.GroupLayout(registerSupplierPanel);
        registerSupplierPanel.setLayout(registerSupplierPanelLayout);
        registerSupplierPanelLayout.setHorizontalGroup(
            registerSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerSupplierPanelLayout.setVerticalGroup(
            registerSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerSupplierPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        productTabbedPane.addTab("Registro de proveedores", registerSupplierPanel);

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productTabbedPane))
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addComponent(productTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        mainMenu.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/box-open.png")), productsPanel); // NOI18N

        registerEmployeePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                registerEmployeePanelComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                registerEmployeePanelComponentShown(evt);
            }
        });

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(employeeTable);
        employeeTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(2).setResizable(false);
        }

        employeeAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        employeeAddButton.setText("Añadir");
        employeeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeAddButtonActionPerformed(evt);
            }
        });

        employeeEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        employeeEditButton.setText("Editar");
        employeeEditButton.setEnabled(false);
        employeeEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeEditButtonActionPerformed(evt);
            }
        });

        employeeDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        employeeDeleteButton.setText("Eliminar");
        employeeDeleteButton.setEnabled(false);
        employeeDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeAddButton)
                .addGap(18, 18, 18)
                .addComponent(employeeEditButton)
                .addGap(18, 18, 18)
                .addComponent(employeeDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(employeeAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(employeeDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerEmployeePanelLayout = new javax.swing.GroupLayout(registerEmployeePanel);
        registerEmployeePanel.setLayout(registerEmployeePanelLayout);
        registerEmployeePanelLayout.setHorizontalGroup(
            registerEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerEmployeePanelLayout.setVerticalGroup(
            registerEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        peopleTabbedPane.addTab("Registro de empleado", registerEmployeePanel);

        registerUserPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                registerUserPanelComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                registerUserPanelComponentShown(evt);
            }
        });

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "RUC", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(userTable);
        userTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(2).setResizable(false);
        }

        userAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        userAddButton.setText("Añadir");
        userAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAddButtonActionPerformed(evt);
            }
        });

        userEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        userEditButton.setText("Editar");
        userEditButton.setEnabled(false);
        userEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEditButtonActionPerformed(evt);
            }
        });

        userDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        userDeleteButton.setText("Eliminar");
        userDeleteButton.setEnabled(false);
        userDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userAddButton)
                .addGap(18, 18, 18)
                .addComponent(userEditButton)
                .addGap(18, 18, 18)
                .addComponent(userDeleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(userDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userEditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout registerUserPanelLayout = new javax.swing.GroupLayout(registerUserPanel);
        registerUserPanel.setLayout(registerUserPanelLayout);
        registerUserPanelLayout.setHorizontalGroup(
            registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        registerUserPanelLayout.setVerticalGroup(
            registerUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );

        peopleTabbedPane.addTab("Registro de usuarios", registerUserPanel);

        javax.swing.GroupLayout peoplePanelLayout = new javax.swing.GroupLayout(peoplePanel);
        peoplePanel.setLayout(peoplePanelLayout);
        peoplePanelLayout.setHorizontalGroup(
            peoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peoplePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleTabbedPane))
        );
        peoplePanelLayout.setVerticalGroup(
            peoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peoplePanelLayout.createSequentialGroup()
                .addComponent(peopleTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        mainMenu.addTab("Personas", new javax.swing.ImageIcon(getClass().getResource("/user.png")), peoplePanel); // NOI18N

        registerEmployeePanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                registerEmployeePanel1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                registerEmployeePanel1ComponentShown(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-pdf.png"))); // NOI18N
        jButton1.setText("Generar Reporte de Productos (.pdf)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file-pdf.png"))); // NOI18N
        jButton2.setText("Generar Reporte de Proveedores (.pdf)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerEmployeePanel1Layout = new javax.swing.GroupLayout(registerEmployeePanel1);
        registerEmployeePanel1.setLayout(registerEmployeePanel1Layout);
        registerEmployeePanel1Layout.setHorizontalGroup(
            registerEmployeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerEmployeePanel1Layout.createSequentialGroup()
                .addGroup(registerEmployeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 362, Short.MAX_VALUE))
        );
        registerEmployeePanel1Layout.setVerticalGroup(
            registerEmployeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerEmployeePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        peopleTabbedPane1.addTab("Reporte de productos", registerEmployeePanel1);

        registerUserPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                registerUserPanel1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                registerUserPanel1ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout registerUserPanel1Layout = new javax.swing.GroupLayout(registerUserPanel1);
        registerUserPanel1.setLayout(registerUserPanel1Layout);
        registerUserPanel1Layout.setHorizontalGroup(
            registerUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        registerUserPanel1Layout.setVerticalGroup(
            registerUserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        peopleTabbedPane1.addTab("Reporte de personas", registerUserPanel1);

        javax.swing.GroupLayout reportsPanelLayout = new javax.swing.GroupLayout(reportsPanel);
        reportsPanel.setLayout(reportsPanelLayout);
        reportsPanelLayout.setHorizontalGroup(
            reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleTabbedPane1))
        );
        reportsPanelLayout.setVerticalGroup(
            reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsPanelLayout.createSequentialGroup()
                .addComponent(peopleTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        mainMenu.addTab("Reportes", new javax.swing.ImageIcon(getClass().getResource("/file-download.png")), reportsPanel); // NOI18N

        javax.swing.GroupLayout configurationPanelLayout = new javax.swing.GroupLayout(configurationPanel);
        configurationPanel.setLayout(configurationPanelLayout);
        configurationPanelLayout.setHorizontalGroup(
            configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        configurationPanelLayout.setVerticalGroup(
            configurationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        mainMenu.addTab("Configuración", new javax.swing.ImageIcon(getClass().getResource("/wrench.png")), configurationPanel); // NOI18N

        javax.swing.GroupLayout peoplePanel6Layout = new javax.swing.GroupLayout(peoplePanel6);
        peoplePanel6.setLayout(peoplePanel6Layout);
        peoplePanel6Layout.setHorizontalGroup(
            peoplePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        peoplePanel6Layout.setVerticalGroup(
            peoplePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Control de productos", peoplePanel6);

        javax.swing.GroupLayout peoplePanel7Layout = new javax.swing.GroupLayout(peoplePanel7);
        peoplePanel7.setLayout(peoplePanel7Layout);
        peoplePanel7Layout.setHorizontalGroup(
            peoplePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        peoplePanel7Layout.setVerticalGroup(
            peoplePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Control de empleados", peoplePanel7);

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        mainMenu.addTab("Control", new javax.swing.ImageIcon(getClass().getResource("/user-check.png")), controlPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(mainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadCategoryTable() {
        categoryTable.setVisible(false);
        Either<String, TableModel> response = new CategoryController().onLoad();
        if (response.isRight()) {
            categoryTable.setModel(response.right().get());
        }
        if (response.isLeft()) {
            JOptionPane.showMessageDialog(null, response.left().get(), "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
        categoryTable.setVisible(true);
    }
    
    private void loadSupplierTable() {
        supplierTable.setVisible(false);
        Either<String, TableModel> response = new SupplierController().onLoad();
        if (response.isRight()) {
            supplierTable.setModel(response.right().get());
        }
        if (response.isLeft()) {
            JOptionPane.showMessageDialog(null, response.left().get(), "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
        supplierTable.setVisible(true);
    }
    
    private void loadProductTable() {
        productTable.setVisible(false);
        Either<String, ArrayList<ProductModel>> productsResponse = new ProductProvider().getProducts();
        if (productsResponse.isRight()) {
            this.products = productsResponse.right().get();
        }
        Either<String, TableModel> response = new ProductController().onLoad();
        if (response.isRight()) {
            productTable.setModel(response.right().get());
        }
        if (response.isLeft()) {
            JOptionPane.showMessageDialog(null, response.left().get(), "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
        productTable.setVisible(true);
    }

    private void loadEmployeeTable() {
        employeeTable.setVisible(false);
        Either<String, TableModel> response = new EmployeeController().onLoad();
        if (response.isRight()) {
            employeeTable.setModel(response.right().get());
        }
        if (response.isLeft()) {
            JOptionPane.showMessageDialog(null, response.left().get(), "Advertencia", JOptionPane.ERROR_MESSAGE);
        }
        employeeTable.setVisible(true);
    }
    
    private void registerCategoryPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerCategoryPanelComponentShown
        this.loadCategoryTable();
    }//GEN-LAST:event_registerCategoryPanelComponentShown

    private void categoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryTableMouseClicked
        if (evt.getClickCount() == 1) {
            categoryEditButton.setEnabled(true);
            categoryDeleteButton.setEnabled(true);
        }
    }//GEN-LAST:event_categoryTableMouseClicked

    private void categoryDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryDeleteButtonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar esta categoría?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            int selectedRow = categoryTable.getSelectedRow();
            String categoryId = categoryTable.getValueAt(selectedRow, 0).toString();
            Either<String, String> response = new CategoryController().onDelete(categoryId);
            if (response.isRight()) {
                JOptionPane.showMessageDialog(null, response.right().get());
                this.loadCategoryTable();
            } else {
                JOptionPane.showMessageDialog(null, response.left().get());
            }
        }
        categoryEditButton.setEnabled(false);
        categoryDeleteButton.setEnabled(false);
    }//GEN-LAST:event_categoryDeleteButtonActionPerformed

    private void registerCategoryPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerCategoryPanelComponentHidden
        // TODO add your handling code here:
        categoryEditButton.setEnabled(false);
        categoryDeleteButton.setEnabled(false);
    }//GEN-LAST:event_registerCategoryPanelComponentHidden

    private void categoryEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryEditButtonActionPerformed
        // TODO add your handling code here:
        CategoryModel categoryModel = new CategoryModel();
        int selectedRow = categoryTable.getSelectedRow();
        categoryModel.setID(categoryTable.getValueAt(selectedRow, 0).toString());
        categoryModel.setName(categoryTable.getValueAt(selectedRow, 1).toString());
        categoryModel.setDescription(categoryTable.getValueAt(selectedRow, 2).toString());
        EditCategorySreen editCategorySreen = new EditCategorySreen(categoryModel);
        editCategorySreen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadCategoryTable();
                categoryEditButton.setEnabled(false);
                categoryDeleteButton.setEnabled(false);
            }
        });
        editCategorySreen.pack();
        editCategorySreen.setResizable(false);
        editCategorySreen.setLocationRelativeTo(null);
        editCategorySreen.setVisible(true);
    }//GEN-LAST:event_categoryEditButtonActionPerformed

    private void categoryAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryAddButtonActionPerformed
        AddCategorySreen addCategorySreen = new AddCategorySreen();
        addCategorySreen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadCategoryTable();
                categoryEditButton.setEnabled(false);
                categoryDeleteButton.setEnabled(false);
            }
        });
        addCategorySreen.pack();
        addCategorySreen.setResizable(false);
        addCategorySreen.setLocationRelativeTo(null);
        addCategorySreen.setVisible(true);
    }//GEN-LAST:event_categoryAddButtonActionPerformed

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            supplierEditButton.setEnabled(true);
            supplierDeleteButton.setEnabled(true);
        }
    }//GEN-LAST:event_supplierTableMouseClicked

    private void supplierAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierAddButtonActionPerformed
        // TODO add your handling code here:
        AddSupplierSreen addSupplierSreen = new AddSupplierSreen();
        addSupplierSreen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadSupplierTable();
                supplierEditButton.setEnabled(false);
                supplierDeleteButton.setEnabled(false);
            }
        });
        addSupplierSreen.pack();
        addSupplierSreen.setResizable(false);
        addSupplierSreen.setLocationRelativeTo(null);
        addSupplierSreen.setVisible(true);
    }//GEN-LAST:event_supplierAddButtonActionPerformed

    private void supplierEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierEditButtonActionPerformed
        // TODO add your handling code here:
        SupplierModel supplierModel = new SupplierModel();
        int selectedRow = supplierTable.getSelectedRow();
        supplierModel.setID(supplierTable.getValueAt(selectedRow, 0).toString());
        supplierModel.setName(supplierTable.getValueAt(selectedRow, 1).toString());
        supplierModel.setRuc(supplierTable.getValueAt(selectedRow, 2).toString());
        supplierModel.setPhone(supplierTable.getValueAt(selectedRow, 3).toString());
        EditSupplierSreen editSupplierSreen = new EditSupplierSreen(supplierModel);
        editSupplierSreen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadSupplierTable();
                supplierEditButton.setEnabled(false);
                supplierDeleteButton.setEnabled(false);
            }
        });
        editSupplierSreen.pack();
        editSupplierSreen.setResizable(false);
        editSupplierSreen.setLocationRelativeTo(null);
        editSupplierSreen.setVisible(true);
    }//GEN-LAST:event_supplierEditButtonActionPerformed

    private void supplierDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierDeleteButtonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este proveedor?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            int selectedRow = supplierTable.getSelectedRow();
            String id = supplierTable.getValueAt(selectedRow, 0).toString();
            Either<String, String> response = new SupplierController().onDelete(id);
            if (response.isRight()) {
                JOptionPane.showMessageDialog(null, response.right().get());
                this.loadSupplierTable();
            } else {
                JOptionPane.showMessageDialog(null, response.left().get());
            }
        }
        supplierEditButton.setEnabled(false);
        supplierDeleteButton.setEnabled(false);
    }//GEN-LAST:event_supplierDeleteButtonActionPerformed

    private void registerSupplierPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerSupplierPanelComponentHidden
        // TODO add your handling code here:
        supplierEditButton.setEnabled(false);
        supplierDeleteButton.setEnabled(false);
    }//GEN-LAST:event_registerSupplierPanelComponentHidden

    private void registerSupplierPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerSupplierPanelComponentShown
        // TODO add your handling code here:
        this.loadSupplierTable();
    }//GEN-LAST:event_registerSupplierPanelComponentShown

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        if (evt.getClickCount() == 1) {
            productEditButton.setEnabled(true);
            productDeleteButton.setEnabled(true);
        }
    }//GEN-LAST:event_productTableMouseClicked

    private void productAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAddButtonActionPerformed
        // TODO add your handling code here:
        AddProductSreen screen = new AddProductSreen();
        screen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadProductTable();
                productEditButton.setEnabled(false);
                productDeleteButton.setEnabled(false);
            }
        });
        screen.pack();
        screen.setResizable(false);
        screen.setLocationRelativeTo(null);
        screen.setVisible(true);
    }//GEN-LAST:event_productAddButtonActionPerformed

    private void productEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productEditButtonActionPerformed
        ProductModel product = new ProductModel();
        int selectedRow = productTable.getSelectedRow();
        product = products.get(selectedRow);
        EditProductSreen screen = new EditProductSreen(product);
        screen.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                loadProductTable();
                productEditButton.setEnabled(false);
                productDeleteButton.setEnabled(false);
            }
        });
        screen.pack();
        screen.setResizable(false);
        screen.setLocationRelativeTo(null);
        screen.setVisible(true);
    }//GEN-LAST:event_productEditButtonActionPerformed

    private void productDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productDeleteButtonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este pruducto?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            int selectedRow = productTable.getSelectedRow();
            String id = productTable.getValueAt(selectedRow, 0).toString();
            Either<String, String> response = new ProductController().onDelete(id);
            if (response.isRight()) {
                JOptionPane.showMessageDialog(null, response.right().get());
                this.loadProductTable();
            } else {
                JOptionPane.showMessageDialog(null, response.left().get());
            }
        }
        productEditButton.setEnabled(false);
        productDeleteButton.setEnabled(false);
    }//GEN-LAST:event_productDeleteButtonActionPerformed

    private void registerProductoPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerProductoPanelComponentHidden
        productEditButton.setEnabled(false);
        productDeleteButton.setEnabled(false);
    }//GEN-LAST:event_registerProductoPanelComponentHidden

    private void registerProductoPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerProductoPanelComponentShown
        // TODO add your handling code here:
        this.loadProductTable();
    }//GEN-LAST:event_registerProductoPanelComponentShown

    private void closeSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSessionButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeSessionButtonActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        if (evt.getClickCount() == 1) {
            employeeEditButton.setEnabled(true);
            employeeDeleteButton.setEnabled(true);
        }
    }//GEN-LAST:event_employeeTableMouseClicked

    private void employeeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeAddButtonActionPerformed

    private void employeeEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeEditButtonActionPerformed

    private void employeeDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDeleteButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este empleado?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            int selectedRow = employeeTable.getSelectedRow();
            String id = employeeTable.getValueAt(selectedRow, 0).toString();
            Either<String, String> response = new EmployeeController().onDelete(id);
            if (response.isRight()) {
                JOptionPane.showMessageDialog(null, response.right().get());
                this.loadProductTable();
            } else {
                JOptionPane.showMessageDialog(null, response.left().get());
            }
        }
        employeeEditButton.setEnabled(false);
        employeeDeleteButton.setEnabled(false);
    }//GEN-LAST:event_employeeDeleteButtonActionPerformed

    private void registerEmployeePanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerEmployeePanelComponentHidden
        employeeEditButton.setEnabled(false);
        employeeDeleteButton.setEnabled(false);
    }//GEN-LAST:event_registerEmployeePanelComponentHidden

    private void registerEmployeePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerEmployeePanelComponentShown
        this.loadEmployeeTable();
    }//GEN-LAST:event_registerEmployeePanelComponentShown

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userTableMouseClicked

    private void userAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAddButtonActionPerformed

    private void userEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEditButtonActionPerformed

    private void userDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDeleteButtonActionPerformed

    private void registerUserPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerUserPanelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUserPanelComponentHidden

    private void registerUserPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerUserPanelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUserPanelComponentShown

    private void registerEmployeePanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerEmployeePanel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_registerEmployeePanel1ComponentHidden

    private void registerEmployeePanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerEmployeePanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_registerEmployeePanel1ComponentShown

    private void registerUserPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerUserPanel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUserPanel1ComponentHidden

    private void registerUserPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_registerUserPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUserPanel1ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new ReportsController().generateProductsReport();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new ReportsController().generateSupplierReport();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserModel user = new UserModel();
                JFrame frame = new MainScreen(user);
                frame.setResizable(false);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categoryAddButton;
    private javax.swing.JButton categoryDeleteButton;
    private javax.swing.JButton categoryEditButton;
    private javax.swing.JTable categoryTable;
    private javax.swing.JButton closeSessionButton;
    private javax.swing.JPanel configurationPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton employeeAddButton;
    private javax.swing.JButton employeeDeleteButton;
    private javax.swing.JButton employeeEditButton;
    private javax.swing.JTable employeeTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane mainMenu;
    private javax.swing.JPanel peoplePanel;
    private javax.swing.JPanel peoplePanel6;
    private javax.swing.JPanel peoplePanel7;
    private javax.swing.JTabbedPane peopleTabbedPane;
    private javax.swing.JTabbedPane peopleTabbedPane1;
    private javax.swing.JButton productAddButton;
    private javax.swing.JButton productDeleteButton;
    private javax.swing.JButton productEditButton;
    private javax.swing.JTabbedPane productTabbedPane;
    private javax.swing.JTable productTable;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JPanel registerCategoryPanel;
    private javax.swing.JPanel registerEmployeePanel;
    private javax.swing.JPanel registerEmployeePanel1;
    private javax.swing.JPanel registerProductoPanel;
    private javax.swing.JPanel registerSupplierPanel;
    private javax.swing.JPanel registerUserPanel;
    private javax.swing.JPanel registerUserPanel1;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JButton supplierAddButton;
    private javax.swing.JButton supplierDeleteButton;
    private javax.swing.JButton supplierEditButton;
    private javax.swing.JTable supplierTable;
    private javax.swing.JButton userAddButton;
    private javax.swing.JButton userDeleteButton;
    private javax.swing.JButton userEditButton;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
